import { StyleSheet } from 'react-native';
import { elevation, space, radius, typography, spacing, type Theme } from '../../theme';

/**
 * Shared visual language for Sign In / Sign Up: calm surfaces, hairline borders,
 * restrained shadow, pill primary CTA — aligned with WelcomeIntro onboarding.
 */
export function makeAuthChromeStyles(t: Theme) {
  return StyleSheet.create({
    outer: { flex: 1, backgroundColor: t.bg },
    scrollView: { flex: 1 },
    /** Scroll body: grow to viewport height and vertically center short content; still scrolls when tall. */
    scrollContent: {
      flexGrow: 1,
      justifyContent: 'center',
      width: '100%',
      paddingHorizontal: space[5],
    },
    /** Wraps brand + form so they move as one centered column. */
    authMainBlock: {
      width: '100%',
    },
    brand: { alignItems: 'center', marginBottom: space[6], gap: space[2] },
    logoCircle: {
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: t.accentLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: t.accentBorder,
      alignItems: 'center',
      justifyContent: 'center',
    },
    logoText: { fontSize: 36, fontWeight: '800', color: t.accent },
    appName: {
      ...typography.title,
      color: t.text,
      fontWeight: '700',
      letterSpacing: -0.5,
      textAlign: 'center',
    },
    tagline: { ...typography.body, color: t.textSecondary, textAlign: 'center' },
    formCard: {
      backgroundColor: t.surface,
      borderRadius: radius.xxl,
      padding: space[5],
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: t.border,
      ...elevation(1, t.shadow),
    },
    formTitle: {
      ...typography.heading,
      fontSize: 24,
      lineHeight: 30,
      letterSpacing: -0.35,
      fontWeight: '800',
      color: t.text,
      textAlign: 'center',
      width: '100%',
    },
    label: {
      ...typography.caption,
      fontWeight: '600',
      color: t.textSecondary,
      marginBottom: space[2],
    },
    input: {
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: t.border,
      borderRadius: radius.lg,
      paddingHorizontal: space[4],
      paddingVertical: space[3],
      // layout-exception: 52pt row for comfortable field tap + readable line height
      minHeight: 52,
      ...typography.body,
      fontSize: 17,
      lineHeight: 22,
      color: t.text,
      backgroundColor: t.bg,
      marginBottom: space[3] + space[1],
    },
    errorBox: {
      backgroundColor: t.errorSurface,
      borderRadius: radius.md,
      padding: space[3],
      marginBottom: space[3] + space[1],
      alignItems: 'center',
    },
    errorText: { ...typography.caption, color: t.error, textAlign: 'center' },
    primaryButton: {
      backgroundColor: t.accent,
      borderRadius: radius.pill,
      // layout-exception: 56pt matches WelcomeIntro primary CTA
      height: 56,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: space[2],
      marginBottom: space[4],
      ...elevation(2, t.accent),
    },
    primaryButtonText: {
      ...typography.subhead,
      fontSize: 17,
      fontWeight: '700',
      color: t.surface,
      letterSpacing: -0.1,
      textAlign: 'center',
    },
    toggleBtn: {
      flexDirection: 'row',
      justifyContent: 'center',
      flexWrap: 'wrap',
      paddingVertical: space[2],
    },
    toggleText: { ...typography.callout, color: t.textSecondary },
    toggleLink: { ...typography.callout, color: t.accent, fontWeight: '600' },
    successOuter: {
      flex: 1,
      backgroundColor: t.bg,
      paddingHorizontal: space[5],
      justifyContent: 'center',
    },
    successCard: {
      backgroundColor: t.surface,
      borderRadius: radius.xxl,
      paddingVertical: space[6],
      paddingHorizontal: space[6],
      alignItems: 'center',
      gap: space[4],
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: t.border,
      ...elevation(1, t.shadow),
    },
    successIconWrap: {
      padding: space[2],
      borderRadius: radius.pill,
      backgroundColor: t.surfaceAlt,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: t.borderLight,
    },
    successTitle: {
      ...typography.title,
      fontSize: 24,
      lineHeight: 30,
      fontWeight: '800',
      letterSpacing: -0.35,
      color: t.text,
      textAlign: 'center',
      width: '100%',
    },
    successDescBlock: {
      width: '100%',
      textAlign: 'center',
    },
    successDescBody: {
      ...typography.body,
      fontSize: 16,
      lineHeight: 24,
      color: t.textSecondary,
    },
    successEmailMark: {
      ...typography.subhead,
      fontSize: 15,
      fontWeight: '600',
      color: t.text,
      backgroundColor: t.accentLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: t.accentBorder,
      paddingVertical: space[1] + 1,
      paddingHorizontal: space[2],
      borderRadius: radius.md,
      overflow: 'hidden',
    },
    /** successCard uses alignItems: 'center', so default primary CTAs would shrink-wrap; stretch + padding matches form CTAs. */
    successPrimaryButton: {
      alignSelf: 'stretch',
      paddingHorizontal: space[5],
    },
    secondaryGhost: {
      alignSelf: 'center',
      paddingVertical: spacing.md,
      marginTop: spacing.xs,
    },
    secondaryGhostText: {
      ...typography.callout,
      color: t.accent,
      fontWeight: '600',
      textAlign: 'center',
    },
    stepHint: {
      ...typography.caption,
      color: t.textTertiary,
      marginBottom: spacing.xl,
      textAlign: 'center',
      width: '100%',
    },
    inviteBody: {
      ...typography.body,
      color: t.textSecondary,
      marginBottom: space[4],
      textAlign: 'center',
      width: '100%',
    },
  });
}
